---
- hosts: all
  become: true
  pre_tasks:

  - name: update repos
    package:
      update_cache: yes


- hosts: web_servers
  become: true
  tasks:

  - name: install apache & PHP packages
    package:
      name:
        - "{{ apache_pack }}"
        - "{{ php_pack }}"
      state: latest
